version: '3.1'

services:
  php:
    image: naiknilesh/php
    build: .
    ports:
      - 80:80
    volumes:
        - ./src:/var/www/html/
  db:
    image: naiknilesh/mysql
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: naiknilesh/adminer
    build: .
    restart: always
    ports:
      - 8181:8181
      
volumes:
  mysql-data: {}
