FROM jenkins/jenkins:lts
USER root
RUN apt-get update &amp;&amp; \
apt-get -y install apt-transport-https \
	ca-certificates \
	curl \
	sshpass \
	gnupg2 \
        ansible \
	software-properties-common &amp;&amp; \
curl -fsSL https://downlaod.docker.com/linux/$(. /etc/os-release; echo "$ID" )/gpg &gt; /tmp/dkey; apt-key
add-apt-respository \
	"deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
	$(lsb_release -cs) \
	stable" &amp;&amp; \
apt-get update &amp;&amp; \
apt-get -y install docker-ce
USER jenkins

