- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Stop Adminer
      shell: docker ps -a -q --filter="name=adminer"
      register: adminer
    - name: Stop Apache/PHP
      shell: docker ps -a -q --filter="name=php:7.4-apache"
      register: apachephp
    - name: Stop Mysql
      shell: docker ps -a -q --filter="name=mysql"			
      register: mysql
    - name: Print the var
      debug:
       var: adminer
       var: apachephp
       var: mysql	
