- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get hostname
      shell: docker stop adminer
      register: result

    - name: Print the var
      debug:
       var: result
