- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Get hostname
      shell: docker ps -a -q --filter="name=<adminer>"
      register: result

    - name: Print the var
      debug:
       var: result
